### ISSUE TITLE
rpmbuild -ba 打包时，openssl报错

### ISSUE THREAD

**Issue by guoxiaodonggit** [weiliang-ms/nginx#1]
spec里定义了openssl，但是SOURCES里没有

**Comment by weiliang-ms** [comment]
需要先执行`make`下载模块包
```
make all
```
可以参考[action](https://github.com/weiliang-ms/nginx/blob/master/.github/workflows/el7.yml) 内的流程

**Comment by guoxiaodonggit** [comment]
好的，明白了，Makefile里的download下载失败，把那四个文件分别下载好，放到SOURCES里，再去掉Makefile里的download就可以了，感谢。
